### ISSUE TITLE
The keyword 'integrated security' is not supported on this platform.

### ISSUE THREAD

**Issue by wklm** [chsakell/aspnet5-angular2-typescript#14]
Hi,
I follow steps in readme to run the project on ubuntu 14.04. Unfortunatelly by step VIIIb (dotnet ef database update) there's following error message: 

wojtek@dell:~/aspnet5-angular2-typescript/src/PhotoGallery$ dotnet ef database update
Project PhotoGallery (.NETCoreApp,Version=v1.0) will be compiled because Input items added from last build
Compiling PhotoGallery for .NETCoreApp,Version=v1.0
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:07.9432541

System.NotSupportedException: The keyword 'integrated security' is not supported on this platform.
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Tools.Cli.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
The keyword 'integrated security' is not supported on this platform.

How can I fix it? 
Cheers, 
Wojtek

**Comment by chsakell** [comment]
Not an expert on that platform but a fellow had created  a pull request which removes the **MS SQL Server dependency** . You might find it helpful. View the pull request [here](https://github.com/chsakell/aspnet5-angular2-typescript/pull/12)

**Comment by gacostab** [comment]
I just checked that project. I think there are differences between his project and yours. 
He is using the DNX CLI libraries to compile the project. 
![dnx](https://cloud.githubusercontent.com/assets/19768984/15843621/ef5d00de-2ca6-11e6-922d-42683c036f57.PNG)

Meanwhile you are using the dotnet libraries from 
![dotnet](https://cloud.githubusercontent.com/assets/19768984/15843637/0ee75fee-2ca7-11e6-9e9b-1b4d5360b2db.PNG)

I think there is an impact in the portability between both libraries.
I tried yours and works fine, meanwhile the other port have issues with the dependencies in v5.0.

Look the following lines.

error: Package Ix-Async 1.2.5 is not compatible with dnxcore50 (DNXCore,Version=v5.0). Package Ix-Async 1.2.5 supports:
error:   - net40 (.NETFramework,Version=v4.0)
error:   - net45 (.NETFramework,Version=v4.5)
error:   - portable-net45+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile78)
error: Package Remotion.Linq 2.0.1 is not compatible with dnxcore50 (DNXCore,Version=v5.0). Package Remotion.Linq 2.0.1 supports:
error:   - net35 (.NETFramework,Version=v3.5)
error:   - net40 (.NETFramework,Version=v4.0)
error:   - net45 (.NETFramework,Version=v4.5)
error:   - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
error: Package Microsoft.CodeAnalysis.CSharp 1.1.0-rc1-20151109-01 is not compatible with dnxcore50 (DNXCore,Version=v5.0). Package Microsoft.CodeAnalysis.CSharp 1.1.0-rc1-20151109-01 supports:
error:   - net45 (.NETFramework,Version=v4.5)
error:   - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)
error: Package Microsoft.CodeAnalysis.Common 1.1.0-rc1-20151109-01 is not compatible with dnxcore50 (DNXCore,Version=v5.0). Package Microsoft.CodeAnalysis.Common 1.1.0-rc1-20151109-01 supports:
error:   - net45 (.NETFramework,Version=v4.5)
error:   - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)
error: One or more packages are incompatible with DNXCore,Version=v5.0.
info : Committing restore...
log  : Writing lock file to disk. Path: /home/juan/deployTest/pgApp2/PhotoGallery/project.lock.json
log  : /home/juan/deployTest/pgApp2/PhotoGallery/project.json
log  : Restore failed in 62881ms.

Errors in /home/juan/deployTest/pgApp2/PhotoGallery/project.json
    Package Ix-Async 1.2.5 is not compatible with dnxcore50 (DNXCore,Version=v5.0). Package Ix-Async 1.2.5 supports:
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile78)
    Package Remotion.Linq 2.0.1 is not compatible with dnxcore50 (DNXCore,Version=v5.0). Package Remotion.Linq 2.0.1 supports:
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
    Package Microsoft.CodeAnalysis.CSharp 1.1.0-rc1-20151109-01 is not compatible with dnxcore50 (DNXCore,Version=v5.0). Package Microsoft.CodeAnalysis.CSharp 1.1.0-rc1-20151109-01 supports:
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)
    Package Microsoft.CodeAnalysis.Common 1.1.0-rc1-20151109-01 is not compatible with dnxcore50 (DNXCore,Version=v5.0). Package Microsoft.CodeAnalysis.Common 1.1.0-rc1-20151109-01 supports:
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)
    One or more packages are incompatible with DNXCore,Version=v5.0.

I'm not quite sure which one is the best framework. I'm still confused with this different versions.

**Comment by italojs** [comment]
do you set Trusted_Connection=true in your connectionString? if yes, remove it

**Comment by Saurab-1010** [comment]
{
//Change the Connection string to below if you are on vs 2022.   
"ConnectionStrings": {
    "EmployeeAppCon": "Server=.; Database=EmployeeDB; Trusted_Connection=True;"
  },
    "Logging": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft.AspNetCore": "Warning"
      }
    },
    "AllowedHosts": "*"

  }
