### ISSUE TITLE
From TSD to Typings

### ISSUE THREAD

**Issue by bcrigler** [chsakell/aspnet5-angular2-typescript#9]
Any update on the change from TSD to Typings in beta.8?  I updated my package and now typescript not completely compiling as the tsResult.js is undefined per this error...

`TypeError: Cannot read property 'pipe' of undefined
    at Gulp.<anonymous> (C:\Users\brian\Dropbox (Personal)\AA\Local Projects\RedsCore\RedsCore\src\RedsCore\gulpfile.js:92:23)
    at module.exports (C:\Users\brian\Dropbox (Personal)\AA\Local Projects\RedsCore\RedsCore\src\RedsCore\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\brian\Dropbox (Personal)\AA\Local Projects\RedsCore\RedsCore\src\RedsCore\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\brian\Dropbox (Personal)\AA\Local Projects\RedsCore\RedsCore\src\RedsCore\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\brian\Dropbox (Personal)\AA\Local Projects\RedsCore\RedsCore\src\RedsCore\node_modules\orchestrator\index.js:134:8)
    at C:\Users\brian\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:141:18)`

**Comment by bcrigler** [comment]
Actually I figured this out on my side and am using Typings now.  I could fork and share if you'd like...  Still using beta.7 though

**Comment by rvhelden** [comment]
If you can
